---
title: "Can the sentiment expressed in trail users' tweets help to assess the effectiveness of Environmental Stewardship Agreements? An exploratory analysis of the Pennine Way National Trail, England"
author: Tom Wilson and Robin Lovelace
output: pdf_document
graphics: yes
---

## Summary
This paper presents an exploratory analysis into the feasibility of using the sentiment expressed within trail users' Twitter messages to assess the effectiveness of Environmental Stewardship Scheme agreements in place along the Pennine Way National Trail, England.

## KEYWORDS:
GIS  |  big data  |  sentiment analysis  |  environmental stewardship  |  volunteered geographic information

## 1. Introduction

The Environmental Stewardship Scheme (ESS), an agri-environmental scheme, represents the most widespread approach to environmental management in England. ESS provides financial rewards to farmers and land managers in return for reductions in farming intensity and the adoption of measures to protect the surrounding environment. The success of early agri-environmental schemes was measured by levels of participation but more recently, and for the lifetime of ESS which was introduced during 2005 and 2006, the focus has shifted to analyse the environmental benefits provided under the scheme (Franks & Emery, 2013), for example with regard to landscape character (Natural England, 2014a), the enhancement of grassland, moorland and heath (Natural England, 2014b), bird populations (Davey et al., 2010), and the provision of ecocsystem services (Defra, 2009).

England has 15 designated National Trails which pass through diverse landscapes and expanses of agricultural land, a substantial amount of which is managed under ESS. In 2012 approximately 12 million visits were made to England’s National Trails (Ramblers, 2012). Despite the interactions that trail users unwittingly have with land managed under ESS there is currently no method to specifically obtain their opinions concerning the effectiveness of ESS in preserving and protecting the environment. The opinions of trail users are in fact limited to broad, large-scale qualitative surveys of visitors to the countryside in general, such as the Monitor of Engagement with the Natural Environment (MENE) which examines the adult population’s engagement with the natural environment (Natural England, 2013). The National Trail User Surveys (The Countryside Agency, 2005; Natural England/Countryside Council for Wales, 2007) were discontinued in 2007.

This research aims to address this potential discontinuity of knowledge by exploring the feasibility of utilising the sentiment conveyed in trail users’ Twitter messages (tweets) to assess the effectiveness of ESS specifically from the trail user perspective. This exploratory analysis will focus on the Pennine Way National Trail. We propose a methodology to geographically and lexically filter relevant tweets that originate from the proximity of the trail, and then perform sentiment analysis to extract the sentiment expressed. Finally we will determine whether this information can be used to assess the effectiveness of ESS.

## 2. Related Research

Currently the effectiveness of ESS is measured with regard to the delivery of ES objectives and environmental benefits, for example in the provision of ecocsystem services (Defra, 2009), the effects on landscape character (Natural England, 2014b), the ecological status of grassland, moor and heath (Natural England, 2014a), and the effects on bird populations (Davey et al., 2010). The Monitor of engagement with the Natural Environment (MENE) is a comprehensive nationwide survey which aims to measure the population’s engagement with the natural environment (Natural England, 2013). The MENE survey is a representative but broad approach, and is not specific to trail users.

Sentiment Analysis (SA) is the process of extracting positive or negative opinions from text with the aim of analysing people's sentiment; this is seen as an important task, particularly since our opinions influence our behaviours, and this has led to a particular commercial interest (Liu, 2012). More recently however, the growth of the social web has led to an increased interest in SA of short informal text for the purposes of social research, to gain insights into specific events, and to study the affective dimension of the social web (Thelwall et al., 2012).

This research aims to address the potential shortfall of information regarding trails users’ opinions by conducting SA of short informal text sent via the micro-blogging service Twitter. Specifically we explore whether the sentiment expressed within the tweets of trail users can be used to assess the effectiveness of ES agreements in delivering environmental benefits.

## 3. Study Area

The focus of this research is the 431 km (268 mile) long Pennine Way National Trail (PWNT), the oldest of England’s 15 National Trails which officially opened on 24th April 1965 (Figure 1). Along its route the PWNT crosses agricultural land managed under ESS. For this analysis a 5km spatial buffer was drawn around the PWNT which will hereafter referred to as the PWNT corridor.



```{r, echo=FALSE, fig.width=2, fig.height=4, fig.align="center", fig.cap="Location of the Pennine Way National Trail, England."}
library(png)
library(grid)
img <- readPNG("/Users/tom/Pictures/PennineWayEngland.png")
grid.raster(img)
```

## 4. Data
